// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: authorization.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const relationshipAllowsPermission = `-- name: RelationshipAllowsPermission :one
SELECT EXISTS (
    SELECT 1
    FROM tenant_relationships tr
    WHERE tr.tenant_origem_id = $1
      AND tr.tenant_destino_id = $2
      AND tr.status = 'ativo'
      AND tr.deleted_at IS NULL
      AND $3::text = ANY(tr.permissoes)
)::bool
`

type RelationshipAllowsPermissionParams struct {
	TenantOrigemID  uuid.UUID `json:"tenant_origem_id"`
	TenantDestinoID uuid.UUID `json:"tenant_destino_id"`
	Column3         string    `json:"column_3"`
}

func (q *Queries) RelationshipAllowsPermission(ctx context.Context, arg RelationshipAllowsPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, relationshipAllowsPermission, arg.TenantOrigemID, arg.TenantDestinoID, arg.Column3)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const userHasTenantPermission = `-- name: UserHasTenantPermission :one
SELECT EXISTS (
    SELECT 1
    FROM tenant_users tu
    JOIN roles r ON r.id = tu.role_id
    JOIN role_permissions rp ON rp.role_id = r.id
    JOIN permissions p ON p.id = rp.permission_id
    WHERE tu.user_id = $1
      AND tu.tenant_id = $2
      AND p.codigo = $3
      AND tu.status = 'ativo'
      AND tu.deleted_at IS NULL
      AND r.status = 'ativo'
      AND r.deleted_at IS NULL
)::bool
`

type UserHasTenantPermissionParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
	Codigo   string    `json:"codigo"`
}

func (q *Queries) UserHasTenantPermission(ctx context.Context, arg UserHasTenantPermissionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userHasTenantPermission, arg.UserID, arg.TenantID, arg.Codigo)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
