// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Permission struct {
	ID        uuid.UUID `json:"id"`
	Codigo    string    `json:"codigo"`
	Descricao string    `json:"descricao"`
	CreatedAt time.Time `json:"created_at"`
}

type Property struct {
	ID                   uuid.UUID      `json:"id"`
	TenantDonoID         uuid.UUID      `json:"tenant_dono_id"`
	PropertyTypeID       uuid.NullUUID  `json:"property_type_id"`
	Titulo               string         `json:"titulo"`
	Descricao            sql.NullString `json:"descricao"`
	Status               string         `json:"status"`
	TipoTransacao        string         `json:"tipo_transacao"`
	PrecoVendaCentavos   sql.NullInt64  `json:"preco_venda_centavos"`
	PrecoAluguelCentavos sql.NullInt64  `json:"preco_aluguel_centavos"`
	AreaPrivativaM2      sql.NullInt32  `json:"area_privativa_m2"`
	Quartos              sql.NullInt32  `json:"quartos"`
	Banheiros            sql.NullInt32  `json:"banheiros"`
	VagasGaragem         sql.NullInt32  `json:"vagas_garagem"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DeletedAt            sql.NullTime   `json:"deleted_at"`
}

type PropertyAddress struct {
	ID               uuid.UUID      `json:"id"`
	PropertyID       uuid.UUID      `json:"property_id"`
	Cep              string         `json:"cep"`
	Estado           string         `json:"estado"`
	Cidade           string         `json:"cidade"`
	Bairro           string         `json:"bairro"`
	Logradouro       sql.NullString `json:"logradouro"`
	Numero           sql.NullString `json:"numero"`
	Complemento      sql.NullString `json:"complemento"`
	ExibicaoEndereco string         `json:"exibicao_endereco"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type PropertyType struct {
	ID        uuid.UUID    `json:"id"`
	Codigo    string       `json:"codigo"`
	Nome      string       `json:"nome"`
	Categoria string       `json:"categoria"`
	Status    string       `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	RevokedAt sql.NullTime `json:"revoked_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type Role struct {
	ID        uuid.UUID    `json:"id"`
	TenantID  uuid.UUID    `json:"tenant_id"`
	Nome      string       `json:"nome"`
	Codigo    string       `json:"codigo"`
	Status    string       `json:"status"`
	CreatedAt time.Time    `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type RolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Tenant struct {
	ID              uuid.UUID       `json:"id"`
	Nome            string          `json:"nome"`
	NomeFantasia    sql.NullString  `json:"nome_fantasia"`
	TipoDocumento   sql.NullString  `json:"tipo_documento"`
	NumeroDocumento sql.NullString  `json:"numero_documento"`
	Email           sql.NullString  `json:"email"`
	Telefone        sql.NullString  `json:"telefone"`
	Site            sql.NullString  `json:"site"`
	LogoUrl         sql.NullString  `json:"logo_url"`
	Status          string          `json:"status"`
	Tipo            string          `json:"tipo"`
	Configuracoes   json.RawMessage `json:"configuracoes"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
}

type TenantRelationship struct {
	ID              uuid.UUID      `json:"id"`
	TenantOrigemID  uuid.UUID      `json:"tenant_origem_id"`
	TenantDestinoID uuid.UUID      `json:"tenant_destino_id"`
	Tipo            string         `json:"tipo"`
	Status          string         `json:"status"`
	Permissoes      []string       `json:"permissoes"`
	Observacao      sql.NullString `json:"observacao"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
}

type TenantUser struct {
	ID        uuid.UUID      `json:"id"`
	TenantID  uuid.UUID      `json:"tenant_id"`
	UserID    uuid.UUID      `json:"user_id"`
	Cargo     sql.NullString `json:"cargo"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	RoleID    uuid.NullUUID  `json:"role_id"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Nome      string         `json:"nome"`
	Email     string         `json:"email"`
	SenhaHash string         `json:"senha_hash"`
	Telefone  sql.NullString `json:"telefone"`
	Status    string         `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
}
