// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ping.sql

package queries

import (
	"context"
)

const ping = `-- name: Ping :one
SELECT 1::int AS value
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, ping)
	var value int32
	err := row.Scan(&value)
	return value, err
}
