// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: property_types.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getPropertyTypeByID = `-- name: GetPropertyTypeByID :one
SELECT id, codigo, nome, categoria, status, created_at, updated_at, deleted_at
FROM property_types
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPropertyTypeByID(ctx context.Context, id uuid.UUID) (PropertyType, error) {
	row := q.db.QueryRowContext(ctx, getPropertyTypeByID, id)
	var i PropertyType
	err := row.Scan(
		&i.ID,
		&i.Codigo,
		&i.Nome,
		&i.Categoria,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPropertyTypes = `-- name: ListPropertyTypes :many
SELECT id, codigo, nome, categoria, status, created_at, updated_at, deleted_at
FROM property_types
WHERE deleted_at IS NULL
  AND status = 'ativo'
ORDER BY categoria, nome
`

func (q *Queries) ListPropertyTypes(ctx context.Context) ([]PropertyType, error) {
	rows, err := q.db.QueryContext(ctx, listPropertyTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PropertyType{}
	for rows.Next() {
		var i PropertyType
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Nome,
			&i.Categoria,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
