// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: properties.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPropertiesByTenant = `-- name: CountPropertiesByTenant :one
SELECT count(*)::bigint
FROM properties
WHERE tenant_dono_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR tipo_transacao = $3::text)
  AND ($4::uuid IS NULL OR property_type_id = $4::uuid)
`

type CountPropertiesByTenantParams struct {
	TenantDonoID   uuid.UUID      `json:"tenant_dono_id"`
	Status         sql.NullString `json:"status"`
	TipoTransacao  sql.NullString `json:"tipo_transacao"`
	PropertyTypeID uuid.NullUUID  `json:"property_type_id"`
}

func (q *Queries) CountPropertiesByTenant(ctx context.Context, arg CountPropertiesByTenantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPropertiesByTenant,
		arg.TenantDonoID,
		arg.Status,
		arg.TipoTransacao,
		arg.PropertyTypeID,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (
    tenant_dono_id,
    property_type_id,
    titulo,
    descricao,
    status,
    tipo_transacao,
    preco_venda_centavos,
    preco_aluguel_centavos,
    area_privativa_m2,
    quartos,
    banheiros,
    vagas_garagem
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, tenant_dono_id, property_type_id, titulo, descricao, status, tipo_transacao, preco_venda_centavos, preco_aluguel_centavos, area_privativa_m2, quartos, banheiros, vagas_garagem, created_at, updated_at, deleted_at
`

type CreatePropertyParams struct {
	TenantDonoID         uuid.UUID      `json:"tenant_dono_id"`
	PropertyTypeID       uuid.NullUUID  `json:"property_type_id"`
	Titulo               string         `json:"titulo"`
	Descricao            sql.NullString `json:"descricao"`
	Status               string         `json:"status"`
	TipoTransacao        string         `json:"tipo_transacao"`
	PrecoVendaCentavos   sql.NullInt64  `json:"preco_venda_centavos"`
	PrecoAluguelCentavos sql.NullInt64  `json:"preco_aluguel_centavos"`
	AreaPrivativaM2      sql.NullInt32  `json:"area_privativa_m2"`
	Quartos              sql.NullInt32  `json:"quartos"`
	Banheiros            sql.NullInt32  `json:"banheiros"`
	VagasGaragem         sql.NullInt32  `json:"vagas_garagem"`
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, createProperty,
		arg.TenantDonoID,
		arg.PropertyTypeID,
		arg.Titulo,
		arg.Descricao,
		arg.Status,
		arg.TipoTransacao,
		arg.PrecoVendaCentavos,
		arg.PrecoAluguelCentavos,
		arg.AreaPrivativaM2,
		arg.Quartos,
		arg.Banheiros,
		arg.VagasGaragem,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.TenantDonoID,
		&i.PropertyTypeID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.TipoTransacao,
		&i.PrecoVendaCentavos,
		&i.PrecoAluguelCentavos,
		&i.AreaPrivativaM2,
		&i.Quartos,
		&i.Banheiros,
		&i.VagasGaragem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPropertyByID = `-- name: GetPropertyByID :one
SELECT id, tenant_dono_id, property_type_id, titulo, descricao, status, tipo_transacao, preco_venda_centavos, preco_aluguel_centavos, area_privativa_m2, quartos, banheiros, vagas_garagem, created_at, updated_at, deleted_at
FROM properties
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPropertyByID(ctx context.Context, id uuid.UUID) (Property, error) {
	row := q.db.QueryRowContext(ctx, getPropertyByID, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.TenantDonoID,
		&i.PropertyTypeID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.TipoTransacao,
		&i.PrecoVendaCentavos,
		&i.PrecoAluguelCentavos,
		&i.AreaPrivativaM2,
		&i.Quartos,
		&i.Banheiros,
		&i.VagasGaragem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPropertiesByTenant = `-- name: ListPropertiesByTenant :many
SELECT id, tenant_dono_id, property_type_id, titulo, descricao, status, tipo_transacao, preco_venda_centavos, preco_aluguel_centavos, area_privativa_m2, quartos, banheiros, vagas_garagem, created_at, updated_at, deleted_at
FROM properties
WHERE tenant_dono_id = $1
  AND deleted_at IS NULL
  AND ($4::text IS NULL OR status = $4::text)
  AND ($5::text IS NULL OR tipo_transacao = $5::text)
  AND ($6::uuid IS NULL OR property_type_id = $6::uuid)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPropertiesByTenantParams struct {
	TenantDonoID   uuid.UUID      `json:"tenant_dono_id"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
	Status         sql.NullString `json:"status"`
	TipoTransacao  sql.NullString `json:"tipo_transacao"`
	PropertyTypeID uuid.NullUUID  `json:"property_type_id"`
}

func (q *Queries) ListPropertiesByTenant(ctx context.Context, arg ListPropertiesByTenantParams) ([]Property, error) {
	rows, err := q.db.QueryContext(ctx, listPropertiesByTenant,
		arg.TenantDonoID,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.TipoTransacao,
		arg.PropertyTypeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Property{}
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.TenantDonoID,
			&i.PropertyTypeID,
			&i.Titulo,
			&i.Descricao,
			&i.Status,
			&i.TipoTransacao,
			&i.PrecoVendaCentavos,
			&i.PrecoAluguelCentavos,
			&i.AreaPrivativaM2,
			&i.Quartos,
			&i.Banheiros,
			&i.VagasGaragem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProperty = `-- name: SoftDeleteProperty :exec
UPDATE properties
SET deleted_at = now(), status = 'excluido', updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProperty(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteProperty, id)
	return err
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties
SET
    property_type_id = COALESCE($1, property_type_id),
    titulo = COALESCE($2, titulo),
    descricao = COALESCE($3, descricao),
    status = COALESCE($4, status),
    tipo_transacao = COALESCE($5, tipo_transacao),
    preco_venda_centavos = COALESCE($6, preco_venda_centavos),
    preco_aluguel_centavos = COALESCE($7, preco_aluguel_centavos),
    area_privativa_m2 = COALESCE($8, area_privativa_m2),
    quartos = COALESCE($9, quartos),
    banheiros = COALESCE($10, banheiros),
    vagas_garagem = COALESCE($11, vagas_garagem),
    updated_at = now()
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, tenant_dono_id, property_type_id, titulo, descricao, status, tipo_transacao, preco_venda_centavos, preco_aluguel_centavos, area_privativa_m2, quartos, banheiros, vagas_garagem, created_at, updated_at, deleted_at
`

type UpdatePropertyParams struct {
	PropertyTypeID       uuid.NullUUID  `json:"property_type_id"`
	Titulo               sql.NullString `json:"titulo"`
	Descricao            sql.NullString `json:"descricao"`
	Status               sql.NullString `json:"status"`
	TipoTransacao        sql.NullString `json:"tipo_transacao"`
	PrecoVendaCentavos   sql.NullInt64  `json:"preco_venda_centavos"`
	PrecoAluguelCentavos sql.NullInt64  `json:"preco_aluguel_centavos"`
	AreaPrivativaM2      sql.NullInt32  `json:"area_privativa_m2"`
	Quartos              sql.NullInt32  `json:"quartos"`
	Banheiros            sql.NullInt32  `json:"banheiros"`
	VagasGaragem         sql.NullInt32  `json:"vagas_garagem"`
	ID                   uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error) {
	row := q.db.QueryRowContext(ctx, updateProperty,
		arg.PropertyTypeID,
		arg.Titulo,
		arg.Descricao,
		arg.Status,
		arg.TipoTransacao,
		arg.PrecoVendaCentavos,
		arg.PrecoAluguelCentavos,
		arg.AreaPrivativaM2,
		arg.Quartos,
		arg.Banheiros,
		arg.VagasGaragem,
		arg.ID,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.TenantDonoID,
		&i.PropertyTypeID,
		&i.Titulo,
		&i.Descricao,
		&i.Status,
		&i.TipoTransacao,
		&i.PrecoVendaCentavos,
		&i.PrecoAluguelCentavos,
		&i.AreaPrivativaM2,
		&i.Quartos,
		&i.Banheiros,
		&i.VagasGaragem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
