// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: property_addresses.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const getPropertyAddress = `-- name: GetPropertyAddress :one
SELECT id, property_id, cep, estado, cidade, bairro, logradouro, numero, complemento, exibicao_endereco, created_at, updated_at
FROM property_addresses
WHERE property_id = $1
`

func (q *Queries) GetPropertyAddress(ctx context.Context, propertyID uuid.UUID) (PropertyAddress, error) {
	row := q.db.QueryRowContext(ctx, getPropertyAddress, propertyID)
	var i PropertyAddress
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Cep,
		&i.Estado,
		&i.Cidade,
		&i.Bairro,
		&i.Logradouro,
		&i.Numero,
		&i.Complemento,
		&i.ExibicaoEndereco,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPropertyAddress = `-- name: UpsertPropertyAddress :one
INSERT INTO property_addresses (
    property_id,
    cep,
    estado,
    cidade,
    bairro,
    logradouro,
    numero,
    complemento,
    exibicao_endereco
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (property_id) DO UPDATE SET
    cep = EXCLUDED.cep,
    estado = EXCLUDED.estado,
    cidade = EXCLUDED.cidade,
    bairro = EXCLUDED.bairro,
    logradouro = EXCLUDED.logradouro,
    numero = EXCLUDED.numero,
    complemento = EXCLUDED.complemento,
    exibicao_endereco = EXCLUDED.exibicao_endereco,
    updated_at = now()
RETURNING id, property_id, cep, estado, cidade, bairro, logradouro, numero, complemento, exibicao_endereco, created_at, updated_at
`

type UpsertPropertyAddressParams struct {
	PropertyID       uuid.UUID      `json:"property_id"`
	Cep              string         `json:"cep"`
	Estado           string         `json:"estado"`
	Cidade           string         `json:"cidade"`
	Bairro           string         `json:"bairro"`
	Logradouro       sql.NullString `json:"logradouro"`
	Numero           sql.NullString `json:"numero"`
	Complemento      sql.NullString `json:"complemento"`
	ExibicaoEndereco string         `json:"exibicao_endereco"`
}

func (q *Queries) UpsertPropertyAddress(ctx context.Context, arg UpsertPropertyAddressParams) (PropertyAddress, error) {
	row := q.db.QueryRowContext(ctx, upsertPropertyAddress,
		arg.PropertyID,
		arg.Cep,
		arg.Estado,
		arg.Cidade,
		arg.Bairro,
		arg.Logradouro,
		arg.Numero,
		arg.Complemento,
		arg.ExibicaoEndereco,
	)
	var i PropertyAddress
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.Cep,
		&i.Estado,
		&i.Cidade,
		&i.Bairro,
		&i.Logradouro,
		&i.Numero,
		&i.Complemento,
		&i.ExibicaoEndereco,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
