// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rbac.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const addPermissionToRole = `-- name: AddPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddPermissionToRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) AddPermissionToRole(ctx context.Context, arg AddPermissionToRoleParams) error {
	_, err := q.db.ExecContext(ctx, addPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToTenantUser = `-- name: AssignRoleToTenantUser :exec
UPDATE tenant_users
SET role_id = $3, updated_at = now()
WHERE tenant_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type AssignRoleToTenantUserParams struct {
	TenantID uuid.UUID     `json:"tenant_id"`
	UserID   uuid.UUID     `json:"user_id"`
	RoleID   uuid.NullUUID `json:"role_id"`
}

func (q *Queries) AssignRoleToTenantUser(ctx context.Context, arg AssignRoleToTenantUserParams) error {
	_, err := q.db.ExecContext(ctx, assignRoleToTenantUser, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, nome, codigo, status)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, nome, codigo, status, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Nome     string    `json:"nome"`
	Codigo   string    `json:"codigo"`
	Status   string    `json:"status"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRowContext(ctx, createRole,
		arg.TenantID,
		arg.Nome,
		arg.Codigo,
		arg.Status,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Nome,
		&i.Codigo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, codigo, descricao, created_at
FROM permissions
ORDER BY codigo
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Codigo,
			&i.Descricao,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, nome, codigo, status, created_at, updated_at, deleted_at
FROM roles
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY nome
`

func (q *Queries) ListRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.QueryContext(ctx, listRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Nome,
			&i.Codigo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionsByTenant = `-- name: ListUserPermissionsByTenant :many
SELECT p.codigo
FROM tenant_users tu
JOIN roles r ON r.id = tu.role_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE tu.user_id = $1
  AND tu.tenant_id = $2
  AND tu.status = 'ativo'
  AND tu.deleted_at IS NULL
  AND r.status = 'ativo'
  AND r.deleted_at IS NULL
ORDER BY p.codigo
`

type ListUserPermissionsByTenantParams struct {
	UserID   uuid.UUID `json:"user_id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) ListUserPermissionsByTenant(ctx context.Context, arg ListUserPermissionsByTenantParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserPermissionsByTenant, arg.UserID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var codigo string
		if err := rows.Scan(&codigo); err != nil {
			return nil, err
		}
		items = append(items, codigo)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
