// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: relationships.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createTenantRelationship = `-- name: CreateTenantRelationship :one
INSERT INTO tenant_relationships (
    tenant_origem_id,
    tenant_destino_id,
    tipo,
    status,
    permissoes,
    observacao
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, tenant_origem_id, tenant_destino_id, tipo, status, permissoes, observacao, created_at, updated_at, deleted_at
`

type CreateTenantRelationshipParams struct {
	TenantOrigemID  uuid.UUID      `json:"tenant_origem_id"`
	TenantDestinoID uuid.UUID      `json:"tenant_destino_id"`
	Tipo            string         `json:"tipo"`
	Status          string         `json:"status"`
	Permissoes      []string       `json:"permissoes"`
	Observacao      sql.NullString `json:"observacao"`
}

func (q *Queries) CreateTenantRelationship(ctx context.Context, arg CreateTenantRelationshipParams) (TenantRelationship, error) {
	row := q.db.QueryRowContext(ctx, createTenantRelationship,
		arg.TenantOrigemID,
		arg.TenantDestinoID,
		arg.Tipo,
		arg.Status,
		pq.Array(arg.Permissoes),
		arg.Observacao,
	)
	var i TenantRelationship
	err := row.Scan(
		&i.ID,
		&i.TenantOrigemID,
		&i.TenantDestinoID,
		&i.Tipo,
		&i.Status,
		pq.Array(&i.Permissoes),
		&i.Observacao,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantRelationshipByID = `-- name: GetTenantRelationshipByID :one
SELECT id, tenant_origem_id, tenant_destino_id, tipo, status, permissoes, observacao, created_at, updated_at, deleted_at
FROM tenant_relationships
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantRelationshipByID(ctx context.Context, id uuid.UUID) (TenantRelationship, error) {
	row := q.db.QueryRowContext(ctx, getTenantRelationshipByID, id)
	var i TenantRelationship
	err := row.Scan(
		&i.ID,
		&i.TenantOrigemID,
		&i.TenantDestinoID,
		&i.Tipo,
		&i.Status,
		pq.Array(&i.Permissoes),
		&i.Observacao,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenantRelationships = `-- name: ListTenantRelationships :many
SELECT id, tenant_origem_id, tenant_destino_id, tipo, status, permissoes, observacao, created_at, updated_at, deleted_at
FROM tenant_relationships
WHERE deleted_at IS NULL
  AND (tenant_origem_id = $1 OR tenant_destino_id = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantRelationshipsParams struct {
	TenantOrigemID uuid.UUID `json:"tenant_origem_id"`
	Limit          int32     `json:"limit"`
	Offset         int32     `json:"offset"`
}

func (q *Queries) ListTenantRelationships(ctx context.Context, arg ListTenantRelationshipsParams) ([]TenantRelationship, error) {
	rows, err := q.db.QueryContext(ctx, listTenantRelationships, arg.TenantOrigemID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantRelationship{}
	for rows.Next() {
		var i TenantRelationship
		if err := rows.Scan(
			&i.ID,
			&i.TenantOrigemID,
			&i.TenantDestinoID,
			&i.Tipo,
			&i.Status,
			pq.Array(&i.Permissoes),
			&i.Observacao,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenantRelationship = `-- name: SoftDeleteTenantRelationship :exec
UPDATE tenant_relationships
SET deleted_at = now(), status = 'excluido', updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenantRelationship(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTenantRelationship, id)
	return err
}

const updateTenantRelationship = `-- name: UpdateTenantRelationship :one
UPDATE tenant_relationships
SET
    status = COALESCE($1, status),
    permissoes = COALESCE($2, permissoes),
    observacao = COALESCE($3, observacao),
    updated_at = now()
WHERE id = $4 AND deleted_at IS NULL
RETURNING id, tenant_origem_id, tenant_destino_id, tipo, status, permissoes, observacao, created_at, updated_at, deleted_at
`

type UpdateTenantRelationshipParams struct {
	Status     sql.NullString `json:"status"`
	Permissoes []string       `json:"permissoes"`
	Observacao sql.NullString `json:"observacao"`
	ID         uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTenantRelationship(ctx context.Context, arg UpdateTenantRelationshipParams) (TenantRelationship, error) {
	row := q.db.QueryRowContext(ctx, updateTenantRelationship,
		arg.Status,
		pq.Array(arg.Permissoes),
		arg.Observacao,
		arg.ID,
	)
	var i TenantRelationship
	err := row.Scan(
		&i.ID,
		&i.TenantOrigemID,
		&i.TenantDestinoID,
		&i.Tipo,
		&i.Status,
		pq.Array(&i.Permissoes),
		&i.Observacao,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
