// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tenants.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const countTenants = `-- name: CountTenants :one
SELECT count(*)::bigint
FROM tenants
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR tipo = $2::text)
`

type CountTenantsParams struct {
	Status sql.NullString `json:"status"`
	Tipo   sql.NullString `json:"tipo"`
}

func (q *Queries) CountTenants(ctx context.Context, arg CountTenantsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTenants, arg.Status, arg.Tipo)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    nome,
    nome_fantasia,
    tipo_documento,
    numero_documento,
    email,
    telefone,
    site,
    logo_url,
    status,
    tipo,
    configuracoes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, COALESCE($11, '{}'::jsonb)
)
RETURNING id, nome, nome_fantasia, tipo_documento, numero_documento, email, telefone, site, logo_url, status, tipo, configuracoes, created_at, updated_at, deleted_at
`

type CreateTenantParams struct {
	Nome            string         `json:"nome"`
	NomeFantasia    sql.NullString `json:"nome_fantasia"`
	TipoDocumento   sql.NullString `json:"tipo_documento"`
	NumeroDocumento sql.NullString `json:"numero_documento"`
	Email           sql.NullString `json:"email"`
	Telefone        sql.NullString `json:"telefone"`
	Site            sql.NullString `json:"site"`
	LogoUrl         sql.NullString `json:"logo_url"`
	Status          string         `json:"status"`
	Tipo            string         `json:"tipo"`
	Column11        interface{}    `json:"column_11"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, createTenant,
		arg.Nome,
		arg.NomeFantasia,
		arg.TipoDocumento,
		arg.NumeroDocumento,
		arg.Email,
		arg.Telefone,
		arg.Site,
		arg.LogoUrl,
		arg.Status,
		arg.Tipo,
		arg.Column11,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.NomeFantasia,
		&i.TipoDocumento,
		&i.NumeroDocumento,
		&i.Email,
		&i.Telefone,
		&i.Site,
		&i.LogoUrl,
		&i.Status,
		&i.Tipo,
		&i.Configuracoes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, nome, nome_fantasia, tipo_documento, numero_documento, email, telefone, site, logo_url, status, tipo, configuracoes, created_at, updated_at, deleted_at
FROM tenants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.NomeFantasia,
		&i.TipoDocumento,
		&i.NumeroDocumento,
		&i.Email,
		&i.Telefone,
		&i.Site,
		&i.LogoUrl,
		&i.Status,
		&i.Tipo,
		&i.Configuracoes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, nome, nome_fantasia, tipo_documento, numero_documento, email, telefone, site, logo_url, status, tipo, configuracoes, created_at, updated_at, deleted_at
FROM tenants
WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3::text)
  AND ($4::text IS NULL OR tipo = $4::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Status sql.NullString `json:"status"`
	Tipo   sql.NullString `json:"tipo"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.QueryContext(ctx, listTenants,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.Tipo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.NomeFantasia,
			&i.TipoDocumento,
			&i.NumeroDocumento,
			&i.Email,
			&i.Telefone,
			&i.Site,
			&i.LogoUrl,
			&i.Status,
			&i.Tipo,
			&i.Configuracoes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTenant = `-- name: SoftDeleteTenant :exec
UPDATE tenants
SET deleted_at = now(), status = 'excluido', updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTenant, id)
	return err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
    nome = COALESCE($1, nome),
    nome_fantasia = COALESCE($2, nome_fantasia),
    tipo_documento = COALESCE($3, tipo_documento),
    numero_documento = COALESCE($4, numero_documento),
    email = COALESCE($5, email),
    telefone = COALESCE($6, telefone),
    site = COALESCE($7, site),
    logo_url = COALESCE($8, logo_url),
    status = COALESCE($9, status),
    tipo = COALESCE($10, tipo),
    configuracoes = COALESCE($11, configuracoes),
    updated_at = now()
WHERE id = $12 AND deleted_at IS NULL
RETURNING id, nome, nome_fantasia, tipo_documento, numero_documento, email, telefone, site, logo_url, status, tipo, configuracoes, created_at, updated_at, deleted_at
`

type UpdateTenantParams struct {
	Nome            sql.NullString        `json:"nome"`
	NomeFantasia    sql.NullString        `json:"nome_fantasia"`
	TipoDocumento   sql.NullString        `json:"tipo_documento"`
	NumeroDocumento sql.NullString        `json:"numero_documento"`
	Email           sql.NullString        `json:"email"`
	Telefone        sql.NullString        `json:"telefone"`
	Site            sql.NullString        `json:"site"`
	LogoUrl         sql.NullString        `json:"logo_url"`
	Status          sql.NullString        `json:"status"`
	Tipo            sql.NullString        `json:"tipo"`
	Configuracoes   pqtype.NullRawMessage `json:"configuracoes"`
	ID              uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRowContext(ctx, updateTenant,
		arg.Nome,
		arg.NomeFantasia,
		arg.TipoDocumento,
		arg.NumeroDocumento,
		arg.Email,
		arg.Telefone,
		arg.Site,
		arg.LogoUrl,
		arg.Status,
		arg.Tipo,
		arg.Configuracoes,
		arg.ID,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.NomeFantasia,
		&i.TipoDocumento,
		&i.NumeroDocumento,
		&i.Email,
		&i.Telefone,
		&i.Site,
		&i.LogoUrl,
		&i.Status,
		&i.Tipo,
		&i.Configuracoes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
