// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint
FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR status = $1::text)
`

func (q *Queries) CountUsers(ctx context.Context, status sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers, status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createTenantUser = `-- name: CreateTenantUser :one
INSERT INTO tenant_users (tenant_id, user_id, cargo, status)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, cargo, status, created_at, updated_at, deleted_at, role_id
`

type CreateTenantUserParams struct {
	TenantID uuid.UUID      `json:"tenant_id"`
	UserID   uuid.UUID      `json:"user_id"`
	Cargo    sql.NullString `json:"cargo"`
	Status   string         `json:"status"`
}

func (q *Queries) CreateTenantUser(ctx context.Context, arg CreateTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRowContext(ctx, createTenantUser,
		arg.TenantID,
		arg.UserID,
		arg.Cargo,
		arg.Status,
	)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Cargo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RoleID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (nome, email, senha_hash, telefone, status)
VALUES ($1, lower($2), $3, $4, $5)
RETURNING id, nome, email, senha_hash, telefone, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Nome      string         `json:"nome"`
	Lower     string         `json:"lower"`
	SenhaHash string         `json:"senha_hash"`
	Telefone  sql.NullString `json:"telefone"`
	Status    string         `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Nome,
		arg.Lower,
		arg.SenhaHash,
		arg.Telefone,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTenantUser = `-- name: GetTenantUser :one
SELECT id, tenant_id, user_id, cargo, status, created_at, updated_at, deleted_at, role_id
FROM tenant_users
WHERE tenant_id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTenantUserParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRowContext(ctx, getTenantUser, arg.TenantID, arg.UserID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Cargo,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.RoleID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, nome, email, senha_hash, telefone, status, created_at, updated_at, deleted_at
FROM users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, nome, email, senha_hash, telefone, status, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
		&i.Telefone,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT id, tenant_id, user_id, cargo, status, created_at, updated_at, deleted_at, role_id
FROM tenant_users
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTenantUsersParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, arg ListTenantUsersParams) ([]TenantUser, error) {
	rows, err := q.db.QueryContext(ctx, listTenantUsers, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantUser{}
	for rows.Next() {
		var i TenantUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Cargo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTenants = `-- name: ListUserTenants :many
SELECT id, tenant_id, user_id, cargo, status, created_at, updated_at, deleted_at, role_id
FROM tenant_users
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUserTenants(ctx context.Context, userID uuid.UUID) ([]TenantUser, error) {
	rows, err := q.db.QueryContext(ctx, listUserTenants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantUser{}
	for rows.Next() {
		var i TenantUser
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Cargo,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, nome, email, senha_hash, telefone, status, created_at, updated_at, deleted_at
FROM users
WHERE deleted_at IS NULL
  AND ($3::text IS NULL OR status = $3::text)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32          `json:"limit"`
	Offset int32          `json:"offset"`
	Status sql.NullString `json:"status"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Email,
			&i.SenhaHash,
			&i.Telefone,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
